#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [[ -f "${repo_root}/.env" ]]; then
  set -a
  source "${repo_root}/.env"
  set +a
fi

SOURCE_STORAGE_ENDPOINT="${SOURCE_STORAGE_ENDPOINT:-${STORAGE_ENDPOINT:-}}"
SOURCE_STORAGE_REGION="${SOURCE_STORAGE_REGION:-${STORAGE_REGION:-us-east-1}}"
SOURCE_STORAGE_ACCESS_KEY="${SOURCE_STORAGE_ACCESS_KEY:-${STORAGE_ACCESS_KEY:-}}"
SOURCE_STORAGE_SECRET_KEY="${SOURCE_STORAGE_SECRET_KEY:-${STORAGE_SECRET_KEY:-}}"
SOURCE_STORAGE_BUCKET="${SOURCE_STORAGE_BUCKET:-${STORAGE_BUCKET:-control-propiedades}}"

if [[ -f "${repo_root}/.env.storage.local" ]]; then
  set -a
  source "${repo_root}/.env.storage.local"
  set +a
fi

: "${SOURCE_STORAGE_ENDPOINT:?Define SOURCE_STORAGE_ENDPOINT o STORAGE_ENDPOINT}"
: "${SOURCE_STORAGE_ACCESS_KEY:?Define SOURCE_STORAGE_ACCESS_KEY o STORAGE_ACCESS_KEY}"
: "${SOURCE_STORAGE_SECRET_KEY:?Define SOURCE_STORAGE_SECRET_KEY o STORAGE_SECRET_KEY}"
: "${TARGET_STORAGE_ENDPOINT:?Define TARGET_STORAGE_ENDPOINT en .env.storage.local}"
: "${TARGET_STORAGE_REGION:?Define TARGET_STORAGE_REGION en .env.storage.local}"
: "${TARGET_STORAGE_ACCESS_KEY:?Define TARGET_STORAGE_ACCESS_KEY en .env.storage.local}"
: "${TARGET_STORAGE_SECRET_KEY:?Define TARGET_STORAGE_SECRET_KEY en .env.storage.local}"
: "${TARGET_STORAGE_BUCKET:?Define TARGET_STORAGE_BUCKET en .env.storage.local}"

export SOURCE_STORAGE_ENDPOINT SOURCE_STORAGE_REGION SOURCE_STORAGE_ACCESS_KEY SOURCE_STORAGE_SECRET_KEY SOURCE_STORAGE_BUCKET
export TARGET_STORAGE_ENDPOINT TARGET_STORAGE_REGION TARGET_STORAGE_ACCESS_KEY TARGET_STORAGE_SECRET_KEY TARGET_STORAGE_BUCKET

cd "${repo_root}/apps/api"
go run ./cmd/storage-migrate
